Models/ErrorViewModel.cs
using System;

namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PersonViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    public class Person
    {
        protected string _firstName;
        public int Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { 
            get
            {
                return _firstName;
            }
            set 
            {
                _firstName = value;
            }
        }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date of birth")]
        public DateTime DateOfBirth { get; set; }

        [EmailAddress]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Invalid email address")]
        public string Email {get; set; }
     
        [StringLength(11, MinimumLength = 9, ErrorMessage = "Phone number have at least 9 digits.")] 
        [RegularExpression(@"^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$", ErrorMessage = "Invalid phone number")]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string BirthPlace { get; set; }

        public int Age { 
            get
            { 
                return CalculateAge();
            }
        }
        private int CalculateAge() {
            TimeSpan ts = DateTime.Now - DateOfBirth;

            DateTime age = DateTime.MinValue.AddDays(ts.Days);

            return age.Year - 1; 
        }
        public bool IsGraduated { get; set; }
        public string FullName { 

            get {
                return $"{LastName} {FirstName}";
            }
            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC.Models;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            HttpContext.Session.SetString("SESSION_USER", "Bao Long");
            return View();
        }

        public IActionResult Privacy()
        {
            var user = HttpContext.Session.GetString("SESSION_USER");

            ViewBag.User = user;
            
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RookiesController.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC.Models;
using MVC.Services;

namespace MVC.Controllers
{
    public class RookiesController : Controller
    {
        private readonly ILogger<RookiesController> _logger;
        private readonly IPersonService _personService;
        public RookiesController(ILogger<RookiesController> logger, IPersonService personService)
        {
            _logger = logger;
            _personService = personService;
        }

        public IActionResult Index()
        {
            var persons = _personService.GetAll();

            return View(persons);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Person model)
        {
            if(!ModelState.IsValid)
            {
                ViewBag.Error = "Invalid model !!!";
                return View();
            }

            _personService.Create(model);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var model = _personService.GetOne(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Person model)
        {
            if(!ModelState.IsValid)
            {
                ViewBag.Error = JsonSerializer.Serialize(model);
                return View();
            }

            _personService.Edit(model);

            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            var model = _personService.GetOne(id);

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var person = _personService.GetOne(id);

            HttpContext.Session.SetString($"SESSION_PERSON_{id}", person.FullName);

            _personService.Delete(id);

            return RedirectToAction("Result", new { id = id });
        }

        public IActionResult Result(int id)
        {
            var deletedPerson = HttpContext.Session.GetString($"SESSION_PERSON_{id}");
        
            ViewBag.deletedPerson = deletedPerson;

            return View();
        }

        // public IActionResult GetAllMale()
        // {
        //     var list = persons.Where(person => person.Gender == "Male").ToList();
           
        //     return Json(list);
        // }

        // public IActionResult GetFirstOldest()
        // {
        //     var oldestAge = persons.Select(person => person.Age).Max();

        //     var oldest = persons.Where(person => person.Age == oldestAge).FirstOrDefault();

        //     return Json(oldest);
        // }

        // public IActionResult GetFullNames()
        // {
        //     var list = persons.Select(person => {
        //         return person.FullName;
        //     }).ToList();

        //     return Json(list);
        // }

        // public IActionResult GetPersonsBirthYearEqual(int yearOfBirth)
        // {
        //     var list = persons.Where(person => person.DateOfBirth.Year == 2000).ToList();

        //     return Json(list);
        // }

        // public IActionResult GetPersonsBirthYearGreater(int yearOfBirth)
        // {
        //     var list = persons.Where(person => person.DateOfBirth.Year > 2000).ToList();

        //     return Json(list);
        // }

        // public IActionResult GetPersonsBirthYearLess(int yearOfBirth)
        // {
        //     var list = persons.Where(person => person.DateOfBirth.Year < 2000).ToList();

        //     return Json(list);
        // }

        // public IActionResult FillterPerson(int yearOfBirth, string type)
        // {
        //     switch(type) {

        //         case "equal": 

        //             return GetPersonsBirthYearEqual(yearOfBirth);

        //         case "greater":

        //             return GetPersonsBirthYearGreater(yearOfBirth);

        //         case "less":

        //             return GetPersonsBirthYearLess(yearOfBirth);

        //         default:
                
        //             return new EmptyResult();
        //     }
        // }

        // public IActionResult ExportListToExcel()
        // {
        //     var builder = new StringBuilder();

        //     builder.AppendLine("Fullname,Gender, Age, Phone number");
            
        //     foreach (var person in persons)
        //     {
        //         builder.AppendLine($"{person.FullName},{person.Gender},{person.Age},{person.PhoneNumber}");
        //     }

        //     return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "persons.csv");
        // }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Rookies/Create.cshtml
@model Person
@{
    ViewData["Title"] = "Create new person";
}

<div class="my-5">
        <h3 class="d-inline-block">Create new person</h3>
</div>
<hr/>

<div class="row">
    <div class="col-6 offset-3">
        @using(Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger"})
            </div>
           
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>

Views/Rookies/Detail.cshtml
@model Person
@{
    ViewData["Title"] = "Edit information of person";
}

<div class="my-5">
        <h3 class="d-inline-block">Edit information of person</h3>
</div>
<hr/>

<div class="row">
    <div class="col-6 offset-3">
        @using(Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName)
                <label class = "form-control"> @Html.ValueFor(model => model.FirstName)</label>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName)
                <label class = "form-control"> @Html.ValueFor(model => model.LastName)</label>
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Gender)
                <label class = "form-control"> @Html.ValueFor(model => model.Gender)</label>
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth)
                <label class = "form-control"> @Html.ValueFor(model => model.DateOfBirth)</label>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber)
                <label class = "form-control"> @Html.ValueFor(model => model.PhoneNumber)</label>
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Email)
                <label class = "form-control"> @Html.ValueFor(model => model.Email)</label>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BirthPlace)
               <label class = "form-control"> @Html.ValueFor(model => model.BirthPlace)</label>
            </div>
            <div class="form-group col-12 text-center">
                <a href='@Url.Action("Delete", "Rookies", new {id = Model.Id})' class="btn btn-danger" role="button" aria-pressed="true" 
                            onclick="return confirm('Are you sure you want to delete this person?');"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
            </div>
        }
    </div>
</div>

Views/Rookies/Edit.cshtml
@model Person
@{
    ViewData["Title"] = "Edit information of person";
}

<div class="my-5">
        <h3 class="d-inline-block">Edit information of person</h3>
</div>
<hr/>

<div class="row">
    <div class="col-6 offset-3">
        @using(Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger"})
            </div>
             <div class="form-group">
                @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger"})
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace,  new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger"})
            </div>
           
            <button type="submit" class="btn btn-primary">Submit</button>
        }
    </div>
</div>

Views/Rookies/FirstOldest.cshtml
@{  
   var oldest = ViewData["Oldest"] as Person;   
} 
<h1>Oldest Person:</h1> 
<hr/>
<div>
    @oldest.FullName
    <hr />
</div>

Views/Rookies/Index.cshtml
@{
    ViewData["Title"] = "Rookies";
}

<div class="my-5">
    <h3 class="d-inline-block">Rookies</h3>
    <a href='@Url.Action("Create", "Rookies")' class="btn btn-primary float-right"><i class="fa fa-plus" aria-hidden="true"></i> Create new persons</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="text-center">ID</th>
            <th scope="col">FullName</th>
            <th scope="col">Gender</th>
            <th scope="col">Date of Birth</th>
            <th scope="col">Age</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>

    <tbody>
        @{
            var index = 0;
            foreach (var item in Model)
            {
                <tr>
                    <th scope="row" class="text-center">@(++index)</th>
                    <th class="text-center">@item.Id</th>
                    <td><a href='@Url.Action("Detail", "Rookies", new {id = item.Id})'>@item.FullName</a></td>
                    <td>@item.Gender</td>
                    <td>@(item.DateOfBirth.ToString("dd/MM/yyyy"))</td>
                    <td>@item.Age</td>
                    <td class="text-center" style="width:200px">
                        <a href='@Url.Action("Edit", "Rookies", new {id = item.Id})' class="btn btn-secondary btn-sm" role="button" aria-pressed="true"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
                        <a href='@Url.Action("Delete", "Rookies", new {id = item.Id})' class="btn btn-danger btn-sm" role="button" aria-pressed="true" 
                            onclick="return confirm('Are you sure you want to delete this person?');"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Views/Rookies/Male.cshtml
<h1>Male Persons</h1>
<hr/>
@foreach (var item in Model)
{
    <div>
        @item.FullName
        <hr />
    </div>
}

Views/Rookies/Result.cshtml
@model Person
@{
    ViewData["Title"] = "Result delete a person";
}

<div class="my-5">
    <h3 class="d-inline-block">Person @ViewBag.deletedPerson was removed from the list successfully!</h3>
</div>
<a href='@Url.Action("Index", "Rookies")' class="btn btn-primary">Back to list</a>
<hr/>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>